# Generated by Django 4.1.2 on 2022-10-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeddyBear', '0002_discount_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default=None, upload_to='products/%Y/%m'),
        ),
    ]
