# Generated by Django 4.1.2 on 2022-10-16 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeddyBear', '0003_alter_products_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['id']},
        ),
    ]
