# Generated by Django 4.1.2 on 2022-10-16 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeddyBear', '0004_alter_category_options_alter_products_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='amount_sold',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
