# Generated by Django 4.1.2 on 2022-10-16 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeddyBear', '0006_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
